### ISSUE TITLE
Generating development JavaScript bundle failed undefined ERROR in commons Module not found

### ISSUE THREAD

**Issue by ctorresthrash** [graysonhicks/gatsby-plugin-loadable-components-ssr#22]
I haven't seen this problem anywhere, so i think it would be an interesting case to be aware of. This error appears on development mode:

``` 
ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a local file make
sure that the path is correct.


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a local file make
sure that the path is correct.


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a local file make
sure that the path is correct.


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a local file make
sure that the path is correct.


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a local file make
sure that the path is correct.


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

undefined

If you're trying to use a package make sure that 'undefined' is installed. If you're trying to use a local file make
sure that the path is correct.

failed Building development bundle - 7.366s
ERROR in commons
Module not found: TypeError: Cannot read property 'indexOf' of undefined

ERROR in commons
Module not found: TypeError: Cannot read property 'indexOf' of undefined

ERROR in commons
Module not found: TypeError: Cannot read property 'indexOf' of undefined

ERROR in polyfill
Module not found: TypeError: Cannot read property 'indexOf' of undefined

ERROR in polyfill
Module not found: TypeError: Cannot read property 'indexOf' of undefined

ERROR in polyfill
Module not found: TypeError: Cannot read property 'indexOf' of undefined

webpack compiled with 6 errors

```
I installed the "next" version and tried to resemble [loadable-test](https://github.com/graysonhicks/loadable-test) and the problem still persists, this is my `gatsby info`: 

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: 3.5.1 => 3.5.1
    gatsby-cli: 3.5.0 => 3.5.0
    gatsby-plugin-compile-es6-packages: ^2.1.0 => 2.1.0
    gatsby-plugin-emotion: ^6.5.0 => 6.5.0
    gatsby-plugin-env-variables: ^2.0.0 => 2.1.0
    gatsby-plugin-eslint: ~3.0.0 => 3.0.0
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.5
    gatsby-plugin-google-tagmanager: ^3.5.0 => 3.5.0
    gatsby-plugin-image: ^1.4.0 => 1.5.0
    gatsby-plugin-loadable-components-ssr: next => 2.2.1-beta.2
    gatsby-plugin-manifest: ^3.4.0 => 3.5.0
    gatsby-plugin-offline: ^4.4.0 => 4.5.1
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.5.0
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.3 => 1.6.2
    gatsby-plugin-sharp: ^3.4.1 => 3.5.0
    gatsby-plugin-sitemap: ^4.1.0 => 4.1.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22
    gatsby-source-filesystem: ^3.4.0 => 3.5.0
    gatsby-source-sanity: ^7.0.4 => 7.0.4
    gatsby-transformer-json: ^3.4.0 => 3.5.0
    gatsby-transformer-sharp: ^3.4.0 => 3.5.0
  npmGlobalPackages:
    gatsby: 3.5.0
```

this is how my `gatsby-config` looks like:

```
import { getLocale, getSiteUrl } from '../backend/config/intlConfig';

require('dotenv').config();

const sanityJson = require('../backend/sanity.json');

console.log('sanityJson.api.dataset', sanityJson.api.dataset);

module.exports = {
  plugins: [
    'gatsby-plugin-emotion',
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-loadable-components-ssr',
    {
      resolve: 'gatsby-plugin-react-helmet-canonical-urls',
      options: {
        siteUrl: getSiteUrl(sanityJson.api.dataset),
        noTrailingSlash: false,
      },
    },
    'gatsby-transformer-json',
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'images',
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'countries',
        path: `${__dirname}/src/components/atoms/FormFields/CountryFormField/CountryLists`,
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'data',
        path: `${__dirname}/src/data`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-remove-serviceworker',
    {
      resolve: 'gatsby-source-sanity',
      options: {
        projectId: sanityJson.api.projectId,
        dataset: sanityJson.api.dataset,
        overlayDrafts:
          !process.env.NETLIFY || process.env.GATSBY_PREVIEW_ENV || false,
        watchMode:
          !process.env.NETLIFY || process.env.GATSBY_PREVIEW_ENV || false,
        token: process.env.GATSBY_SANITY_AUTH_TOKEN || '',
      },
    },
    {
      resolve: 'gatsby-plugin-compile-es6-packages',
      options: {
        modules: ['api-runner-ssr', 'hex-rgb'],
      },
    },
    {
      resolve: 'gatsby-plugin-sitemap',
      options: {
        output:
          getLocale(sanityJson.api.dataset) === 'us'
            ? '/csod-sitemap.xml'
            : '/sitemap.xml',
      },
    },
    {
      resolve: 'gatsby-plugin-polyfill-io',
      options: {
        features: ['fetch'],
      },
    },
    {
      resolve: 'gatsby-plugin-robots-txt',
      options: {
        configFile: 'robots-txt.config.js',
      },
    },
    {
      resolve: `gatsby-plugin-env-variables`,
      options: {
        allowList: [
          'NETLIFY',
          'CONTEXT',
          'DEPLOY_PRIME_URL',
          'GATSBY_PREVIEW_ENV',
          'CSOD_ENV',
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-webpack-bundle-analyser-v2',
      options: {
        disable: !process.env.ANALYZE_BUNDLE_SIZE,
        generateStatsFile: true,
        analizerMode: 'static',
      },
    },
  ],
  flags: {
    DEV_SSR: false,
  },
};
```

I'm not sure if there's something wrong on my side or this is a case that hasn't been covered yet.

Thanks beforehand.

**Comment by graysonhicks** [comment]
I notice you have `DEV_SSR` as false, can you try with it true?

**Comment by graysonhicks** [comment]
Also, as this is `next` related, just noting that I released `3.0.0` today. 👍

**Comment by chrisvince** [comment]
@graysonhicks v3 release! Thank you!!

**Comment by ctorresthrash** [comment]
@graysonhicks I tried setting DEV_SSR to true and the problem persists, i ran gatsby clean and did a fresh install and the problem still goes on

**Comment by graysonhicks** [comment]
@ctorresthrash What does your component import look like with loadable?

**Comment by ctorresthrash** [comment]
Hi @graysonhicks I import them like this `const GDPR = loadable(() => import('../../molecules/GDPR/GDPR'));`

**Comment by graysonhicks** [comment]
@ctorresthrash Can you create a minimal reproduction?  Thanks!
